blank_issues_enabled: false
contact_links:
  - name: Kiccha Request
    url: https://t.me/KicchaRequest
    about: Please drop your doubts or queries there for an immediate response.
  - name: Movie Update Channel
    url: https://t.me/gd_film
    about: Basic documentation for setting up.
